name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.2]
    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run : npm config set registry http://registry.npm.taobao.org/
      - run : npm install
#      - name: Build
#      - run:  npm run build-storybook

    
    
