name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  #init 
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.2]
    steps:
      # pull code
      - uses: actions/checkout@v3
      # install
      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run : npm config set registry http://registry.npm.taobao.org/
      - run : npm install
  #build
  build:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.2]
    steps:
      # build
      - name: Build
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
      - run : npm run build-storybook
  #deploy
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.2]
    steps:
      # deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "storybook-static/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}



    
    
