name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.2]
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build
      run: |
        npm config set registry http://registry.npm.taobao.org/
        npm install
        npm run build-storybook
